#!/bin/bash

ip=$(/sbin/ifconfig tun0 | grep 'inet addr': | cut -d: -f2 | cut -d" " -f1)

if [ $ip ]
then
	echo "using VPN"
	dcloud=true
else
	echo "using Ethernet"
	ip=$(/sbin/ifconfig eth0 | grep 'inet addr': | cut -d: -f2 | cut -d" " -f1)
fi
	
echo $ip

if grep -q "odl-netconf" features;
then
	echo "mounting netconf nodes"
	while read -r line
	do
		addr=$(echo $line | cut -f1 -d" ")
		name=$(echo $line | cut -f2 -d" ")
		python/put-node.py localhost $addr $name
		sleep 2

		while true;
		do
      	  		python/is-node-connected.py $ip $name 
	        	if [ $? -eq 0 ]
        		then
                		echo "NETCONF node $name up"
                		break
        		else
                		sleep 2
        		fi
		done
	done < nodes
fi

if grep -q "odl-bgpcep-bgp" features;
then
	echo "configuring BGP"
	# configure BGP RIB
	python/put-bgp-rib.py $ip
	
	# configure app peer	
	python/put-app-rib.py $ip 1.2.3.4 

	if grep -q "odl-netconf" features;
	then
		if $dcloud;
		then	
			# configure BGP peer to talk to ODL
			python/put-bgp-neighbor.py $ip $name 
		fi
	fi

	# configure ODL to talk to BGP peer
	python/put-bgp-peer.py $ip $addr
fi

if grep -q "odl-bgpcep-pcep" features;
then
	if $dcloud;
	then
		echo "configuring PCE-P"
		req='{"request": [{"option": "addPCEP", "pcep_ip":"'$ip'"}]}'
		echo $req
		echo $req | curl -s -X POST http://198.18.133.1:8010/virl_client -H "Content-Type: application/json" -d @-
	fi
fi 
