#!/bin/bash

DISTRO=$(<distro)

mkdir -p $DISTRO/etc/opendaylight/karaf

if grep -q "1MB" $DISTRO/etc/org.ops4j.pax.logging.cfg;
then
	echo "configuring logging and features"
	sed -i 's/1MB/10000MB/' $DISTRO/etc/org.ops4j.pax.logging.cfg
	cat logs >> $DISTRO/etc/org.ops4j.pax.logging.cfg 	

	# add features
	while read -r line
	do
		feature=$(echo $line)
		echo $feature
		sed -i '/^featuresBoot=/ s/$/,'$feature'/' $DISTRO/etc/org.apache.karaf.features.cfg
	done < features	
fi
