#!/bin/bash

if [ $# != 3 ]
then
	echo "usage $0 site (lon/rtp/sng/chi) username password"
	exit 1
fi

echo cisco123 | sudo 
echo $3 | sudo openconnect -u $2 --passwd-on-stdin https://dcloud-$1-anyconnect.cisco.com &

