#!/bin/bash

DISTRO=$(<distro)
rm -rf $DISTRO/data
rm -rf $DISTRO/etc/opendaylight/current
rm -rf $DISTRO/cache
rm -rf $DISTRO/journal
rm -rf $DISTRO/snapshots
rm -rf $DISTRO/instances

source $DISTRO/bin/setenv
$DISTRO/bin/start

while true;
do
	up=$(netstat -an | grep 127.0.0.1:1830 | wc -l)
	if [ $up == 2 ]
	then
		echo "ODL is nearly ready"
		break
	else
		echo "ODL is starting"
		sleep 5
	fi 
done

while true;
do
	ready=$(curl http://admin:admin@localhost:8181/restconf/operational/network-topology:network-topology/topology/topology-netconf/node/controller-config 2>&1)
	if echo $ready | grep -q "connected";
	then
		echo "ODL is ready!"
		exit 0
	else
		echo "ODL is almost ready"
		sleep 5
	fi
done

