#!/bin/bash

DISTRO=$(<distro)
cd OpenDaylight
rm -rf $DISTRO/data
rm -rf $DISTRO/etc/opendaylight/current
rm -rf $DISTRO/cache
rm -rf $DISTRO/journal
rm -rf $DISTRO/snapshots
rm -rf $DISTRO/instances
mkdir -p $DISTRO/etc/opendaylight/karaf

if grep -q "1MB" $DISTRO/etc/org.ops4j.pax.logging.cfg;
then
	sed -i 's/1MB/10000MB/' $DISTRO/etc/org.ops4j.pax.logging.cfg
	cat ../logs >> $DISTRO/etc/org.ops4j.pax.logging.cfg 	
	
	sed -i '/^featuresBoot=/ s/$/,odl-dlux-all,odl-netconf-all,odl-restconf-all,odl-netconf-mdsal,odl-bgpcep-bgp-all,odl-bgpcep-pcep-all,odl-netconf-connector-all/' $DISTRO/etc/org.apache.karaf.features.cfg
fi

source $DISTRO/bin/setenv
$DISTRO/bin/start

while true;
do
	up=$(netstat -an | grep 127.0.0.1:1830 | wc -l)
	if [ $up == 2 ]
	then
		echo "ODL is nearly ready"
		break
	else
		echo "ODL is starting"
		sleep 5
	fi 
done

while true;
do
	ready=$(curl http://admin:admin@localhost:8181/restconf/operational/network-topology:network-topology/topology/topology-netconf/node/controller-config 2>&1)
	if echo $ready | grep -q "connected";
	then
		echo "ODL is ready!"
		exit 0
	else
		echo "ODL is almost ready"
		sleep 5
	fi
done

